### PR TITLE
Update MVF_main.m

### PR DESCRIPTION
**Pull request by adleksey**
fix lost rows index

### CODE REVIEW

**Comment by Yellowbooker** [comment]
> fix lost rows index

Thank you for your comments. The code was written in two years ago and now we have modified it to make it faster and more reasonable. We will update the code in few days.

**Comment by adleksey** [comment]
Thank you, I'll wait for the new version, very interesting to see it

**Comment by Yellowbooker** [comment]
> Thank you, I'll wait for the new version, very interesting to see it

Thank you for the interesting of our codes. Microwave filter is a very small field in the microwave engineering and few peopole are interested in it. Curious, are you a microwave engineer from the US?

**Comment by adleksey** [comment]
> Thank you for the interesting of our codes.
Thank you for MVF v2. I'm researching it right now.

> Curious, are you a microwave engineer from the US?
No.

**Pull request closed without merging**
